### ISSUE TITLE
add check box for enable and disable, list ONLY FOLDERS NAME selection, without files name.

### ISSUE THREAD

**Issue by streikpc** [SanderSade/DirLister#13] opened 2021-03-28 10:21 UTC
Add check box for enable and disable, list ONLY FOLDERS NAME selection, WITHOUT FILES, AND NON RECURSIVE.
Is to use in a script from msdos, and create a list of folders, with or without absolute address of the folder.

**Comment by SanderSade** [comment] 2021-03-29 07:27
Duplicate of #5 and #7

**Closed as completed by SanderSade** 2021-03-29 07:27 UTC
Labels: duplicate
